upstream loadbalancer {
  # Docker internal DNS names: <project>-<service>-<number>
  server quote-demo-web-1:5000;
  server quote-demo-web-2:5000;
  server quote-demo-web-3:5000;
}

server {
  listen 80;
  server_name localhost;
  location / {
    proxy_pass http://loadbalancer;
  }
}
